# Generated by Django 4.0.6 on 2022-07-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('alt_text', models.TextField()),
                ('image_file', models.ImageField(upload_to='')),
            ],
        ),
    ]
